version: '3.4'

services:
  ecoeden.search.api:
    image: ${DOCKER_REGISTRY-}ecoedensearchapi
    build:
      context: .
      dockerfile: Ecoeden.Search.Api/Dockerfile

networks:
  ecoeden_dev_net:
    external: true